/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionBadge: typeof import('./src/components/ConnectionBadge.vue')['default']
    DuplicateImportModal: typeof import('./src/components/DuplicateImportModal.vue')['default']
    ExplorerEntryMenu: typeof import('./src/components/explorer/ExplorerEntryMenu.vue')['default']
    ExplorerFile: typeof import('./src/components/explorer/ExplorerFile.vue')['default']
    ExplorerFolder: typeof import('./src/components/explorer/ExplorerFolder.vue')['default']
    GeneralSettingsPanel: typeof import('./src/components/settings/GeneralSettingsPanel.vue')['default']
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    MobileNavBar: typeof import('./src/components/MobileNavBar.vue')['default']
    PlayerBar: typeof import('./src/components/PlayerBar.vue')['default']
    PlaylistItem: typeof import('./src/components/PlaylistItem.vue')['default']
    PlaylistSelectorFilter: typeof import('./src/components/PlaylistSelectorFilter.vue')['default']
    QueuePanel: typeof import('./src/components/QueuePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarPlaylists: typeof import('./src/components/SidebarPlaylists.vue')['default']
    Song: typeof import('./src/components/Song.vue')['default']
    SongProgress: typeof import('./src/components/SongProgress.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UpdateBadge: typeof import('./src/components/UpdateBadge.vue')['default']
    UScrollArea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue')['default']
    USlider: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    UTabs: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.29.0_@floating-ui+dom@1.7.6_@tiptap+extension-drag-handl_d5808805e2ef10297546d40b66c2abaa/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
